#------------- Environment parameters ----------------
#
# Defines parameters external to the rocket:
#   - Athmosphere parameters
#   - Rail configuration
#   - Targeted apogee
#
# ----------------------------------------------------

ground_altitude: 1567
latitude: 46.90479
longitude: 8.07575
temperature: 300
humidity: 0.5
pressure: 84972.484
apogee: # targeted apogee
  - 0
  - 0
  - 3000
wind_speed: 10
wind_direction: 0 # direction of wind from north, trigonometric
wind_variation: 5.0 # wind speed variability as ratio of wind_speed
rail_azimuth: 0 # angle of rail from north, trigonmetric
rail_zenith: 0 # angle of rail from vertical (trigonmetric inertial Y rotation)
rocket_roll: 0 # initial roll angle around z rocket axis
rail_length: 9
