acc_bias: 0
acc_noise: 0.0
air_density_bias: 20
baro_bias: 0
baro_noise: 0.0
drag_assymetry:
- -0.2
- 0.5
fins_tilt:
- 2
- 1
- -1
gyro_bias: 0
gyro_noise: 0.0
motor_tilt:
- 0.0
- 0.0
plume_tilt_var:
- 0.0
- 0.0
sensor_period: 0.05
wind_gust_assymetry: 0.3
wind_gust_intensity:
- 0
- 0
wind_gust_var: 5
